/* automatically generated by rust-bindgen */

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]

extern crate libc;

#[cfg(not(feature = "bindgen"))]
include!("bindings.rs");
